In [1]:
"""Lab 1"""

import numpy as np

In [2]:
#utwórz tablicę zawierającą 10 zer,
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#utwórz tablicę zawierającą 10 piątek,
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [4]:
#utwórz tablicę zawierającą liczby od 10 do 50,
array_range = np.arange(10, 51, 1)
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [5]:
#utwórz macierz (tablica wielowymiarowa) o wymiarach 3x3 zawierającą liczby od 0 do 8,
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
#utwórz macierz jednostkową o wymiarach 3x3,
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
#utwórz macierz o wymiarach 5x5 zawierającą liczby z dystrybucji normalnej (Gaussa),
np.random.normal(0, 0.5, (5,5))

array([[-0.39096935,  0.0084926 , -0.16978716,  0.14657705,  0.38131939],
       [-1.0404515 , -0.3349533 ,  0.2058156 , -0.40424519,  0.14396252],
       [-0.44431773,  0.81081951,  0.46761944, -0.736759  ,  0.44006224],
       [ 0.71215821,  0.47537853, -0.37095138, -0.58335876,  0.0562123 ],
       [ 0.57575744,  0.78066693,  0.32384564,  0.5468536 ,  0.01009146]])

In [8]:
#utwórz macierz o wymiarach 10x10 zawierającą liczby od 0,01 do 1 z krokiem 0,01,
np.linspace(0.01, 1.0, 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [9]:
#utwórz tablicę zawierającą 20 liniowo rozłożonych liczb między 0 a 1 (włącznie z 0 i 1),
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [10]:
#utwórz tablicę zawierającą losowe liczby z przedziału (1, 25), 
#następnie zamień ją na macierz o wymiarach 5 x 5 z tymi samymi liczbami:
array_random = np.random.randint(2, 25, 25).reshape(5, 5)
print(array_random)

#oblicz sumę wszystkich liczb w ww. macierzy,
print("\nSuma: ", array_random.sum())

#oblicz średnią wszystkich liczb w ww. macierzy,
print("\nŚrednia: ", array_random.mean())

#oblicz standardową dewiację dla liczb w ww. macierzy,
print("\nStandardowa dewiacja: ", np.std(array_random))

#oblicz sumę każdej kolumny ww. macierzy i zapisz ją do tablicy.
array_sum_axis = array_random.sum(axis=0)
print("\nSuma każdej z kolumn: ", array_sum_axis)

[[ 8  8 24  5  5]
 [23 22  2 19 22]
 [ 7  7 15 12 16]
 [16 24 17  4 21]
 [15 15 15 15  8]]

Suma:  345

Średnia:  13.8

Standardowa dewiacja:  6.693280212272605

Suma każdej z kolumn:  [69 76 73 55 72]


In [11]:
#twórz macierz o wymiarach 5x5 zawierającą losowe liczby z przedziału (0, 100) i:
array_5x5 = np.random.randint(1, 100, (5, 5))
print(array_5x5)

#oblicz medianę tych liczb,
print("\nMediana: ", np.median(array_5x5))

#znajdź najmniejszą liczbę tej macierzy,
print("\nNajmniejsza liczba: ", array_5x5.min())

#znajdź największą liczbę tej macierzy.
print("\nNajwieksza liczba: ", array_5x5.max())

[[71 48 50 88 50]
 [71 54 36 84 87]
 [33 27  4 64 57]
 [23  5 21 96 49]
 [54 52 83 21  5]]

Mediana:  50.0

Najmniejsza liczba:  4

Najwieksza liczba:  96


In [12]:
#utwórz macierz o wymiarach różnych od siebie i większych od 1, 
#zawierającą losowe liczby z przedziału (0, 100) i dokonaj jej transpozycji,
matrix1 = np.random.randint(1, 100, (4, 3))
print("Macierz:\n", matrix1)

print("\nTranspozycja:\n", matrix1.T)

Macierz:
 [[ 8 94 37]
 [52 78 59]
 [95 50 24]
 [64 98 54]]

Transpozycja:
 [[ 8 52 95 64]
 [94 78 50 98]
 [37 59 24 54]]


In [13]:
#utwórz dwie macierze o odpowiednich wymiarach (doczytać), większych od 2 i dodaj je do siebie,
array1 = np.random.random((4, 4))
array2 = np.random.random((4, 3))
print("Macierz 1:\n", array1)
print("\nMacierz 2:\n", array2)

array2 = np.append(array2, np.zeros((4, 1)), axis=1)
print("\nMacierz 2 - dodanie kolumny:\n", array2)
print("\nSuma macierzy:\n", array1 + array2)

Macierz 1:
 [[0.63456309 0.13508155 0.09449811 0.93154782]
 [0.25429991 0.38386789 0.7583612  0.71156687]
 [0.93070885 0.72544556 0.32754006 0.6599125 ]
 [0.41946486 0.17857148 0.90810818 0.22545793]]

Macierz 2:
 [[0.17501386 0.70884726 0.55686661]
 [0.27763525 0.97097122 0.03484871]
 [0.10824168 0.24328777 0.05070609]
 [0.67036268 0.50089827 0.22877236]]

Macierz 2 - dodanie kolumny:
 [[0.17501386 0.70884726 0.55686661 0.        ]
 [0.27763525 0.97097122 0.03484871 0.        ]
 [0.10824168 0.24328777 0.05070609 0.        ]
 [0.67036268 0.50089827 0.22877236 0.        ]]

Suma macierzy:
 [[0.80957695 0.84392881 0.65136472 0.93154782]
 [0.53193516 1.35483911 0.79320991 0.71156687]
 [1.03895053 0.96873333 0.37824615 0.6599125 ]
 [1.08982754 0.67946975 1.13688054 0.22545793]]


In [14]:
#utwórz dwie macierze o odpowiednich wymiarach (doczytać) różnych od siebie i większych od 2, 
#a następnie pomnóż je przez siebie za pomocą dwóch różnych funkcji (np. ‘matmul’ i ‘multiply’),
array1 = np.random.random((3, 4))
array2 = np.random.random((4, 3))
print("Macierz 1:\n", array1)
print("\nMacierz 2:\n", array2)

print ("\n\nMnozenie macierzy:\nmatmul:\n", np.matmul(array1, array2))

print ("\nmultiply:\n", np.multiply(array1.T, array2))

Macierz 1:
 [[0.16224532 0.59221713 0.02483463 0.94525152]
 [0.53511776 0.3440101  0.67007512 0.30499776]
 [0.54879852 0.88569968 0.83302175 0.07862702]]

Macierz 2:
 [[0.85174409 0.89877546 0.31850805]
 [0.16695834 0.06534191 0.1042793 ]
 [0.11862622 0.65175678 0.14672764]
 [0.12741621 0.16659836 0.68005697]]


Mnozenie macierzy:
matmul:
 [[0.36045349 0.3581822  0.75990124]
 [0.63156889 0.99096712 0.51204684]
 [0.72414742 1.10714665 0.44285505]]

multiply:
 [[0.13819149 0.48095072 0.17479675]
 [0.09887559 0.02247828 0.09236014]
 [0.00294604 0.436726   0.12222731]
 [0.12044037 0.05081213 0.05347086]]


In [15]:
#dla spóźnialskich: należy krótko opisać i uruchomić wszystkie funkcje (od ‘add’ do ‘lcm’) z sekcji ‘Math operations’
array1 = np.random.randint(1, 20, (1, 5))
array2 = np.random.randint(1, 20, (1, 5))

In [16]:
print("tab1: ", array1)
print("tab2: ", array2)

print("\nDodawanie argumentów:\n", np.add(array1,array2))
print("\nOdejmowanie argumentów:\n", np.subtract(array1,array2))
print("\nMnożenie argumentów:\n", np.multiply(array1,array2))
print("\nDzielenie z resztą argumentów:\n", np.divide(array1,array2))

print("\nLogarytm sumy wykładników potęgi wejściowej:\n", np.logaddexp(array1,array2))
print("\nLogarytm sumy wykładników potęgi wejściowej o podstawie 2:\n", np.logaddexp2(array1,array2))
print("\nDzielenie z resztą argumentów:\n", np.true_divide(array1,array2))
print("\nZaokraglanie dzielenia do liczb calkowitych w dół:\n", np.floor_divide(array1,array2))


tab1:  [[18  7  5  6 16]]
tab2:  [[14 10  3 16 16]]

Dodawanie argumentów:
 [[32 17  8 22 32]]

Odejmowanie argumentów:
 [[  4  -3   2 -10   0]]

Mnożenie argumentów:
 [[252  70  15  96 256]]

Dzielenie z resztą argumentów:
 [[1.28571429 0.7        1.66666667 0.375      1.        ]]

Logarytm sumy wykładników potęgi wejściowej:
 [[18.01814993 10.04858735  5.12692801 16.0000454  16.69314718]]

Logarytm sumy wykładników potęgi wejściowej o podstawie 2:
 [[18.08746284 10.169925    5.32192809 16.00140819 17.        ]]

Dzielenie z resztą argumentów:
 [[1.28571429 0.7        1.66666667 0.375      1.        ]]

Zaokraglanie dzielenia do liczb calkowitych w dół:
 [[1 0 1 0 1]]


In [17]:
print("tab1: ", array1)
print("tab2: ", array2)

print("\nNegacja elementów, wartość przeciwna:\n", np.negative(array1))
print("\nOdpowiednik x.copy (), ale zdefiniowany"\
      "tylko dla typów obsługujących arytmetykę:\n", np.positive(array1))
print("\nPotęgowanie. Pierwsze elementy tablicy"\
      "podniesione do potęg z drugiej tablicy, pod względem elementów:\n", np.power(array1, array2))

print("\nZwraca resztęz dzielenia bez znaku:\n", np.remainder(array1, array2))
print(np.remainder(np.negative(array1), array2))
print("\nZwraca resztęz dzielenia bez znaku:\n", np.mod(array1, array2))
print(np.mod(np.negative(array1), array2))
print("\nZwraca resztęz dzielenia ze znakiem:\n", np.fmod(array1, array2))
print(np.fmod(np.negative(array1), array2))
print("\nZwraca iloraz elementarny i resztę jednocześnie:\n", np.divmod(np.negative(array1), array2))
print("\nWartość bezwzględna:\n", np.absolute(array1))
print(np.absolute(np.negative(array1)))
print(np.fabs(np.negative(array1)))

tab1:  [[18  7  5  6 16]]
tab2:  [[14 10  3 16 16]]

Negacja elementów, wartość przeciwna:
 [[-18  -7  -5  -6 -16]]

Odpowiednik x.copy (), ale zdefiniowanytylko dla typów obsługujących arytmetykę:
 [[18  7  5  6 16]]

Potęgowanie. Pierwsze elementy tablicypodniesione do potęg z drugiej tablicy, pod względem elementów:
 [[374813367582081024          282475249                125
       2821109907456                  0]]

Zwraca resztęz dzielenia bez znaku:
 [[4 7 2 6 0]]
[[10  3  1 10  0]]

Zwraca resztęz dzielenia bez znaku:
 [[4 7 2 6 0]]
[[10  3  1 10  0]]

Zwraca resztęz dzielenia ze znakiem:
 [[4 7 2 6 0]]
[[-4 -7 -2 -6  0]]

Zwraca iloraz elementarny i resztę jednocześnie:
 (array([[-2, -1, -2, -1, -1]]), array([[10,  3,  1, 10,  0]]))

Wartość bezwzględna:
 [[18  7  5  6 16]]
[[18  7  5  6 16]]
[[18.  7.  5.  6. 16.]]


In [18]:
array3 = [2.33, 4.66, -7.5]
print("tab1: ", array1)
print("tab2: ", array2)
print("tab3: ", array3)

print("\nZaokrągla elementy tablicy do najbliższej liczby całkowitej:\n", np.rint(array1))
print(np.rint(array3))
print("\nZwraca elementowe oznaczenie znaku liczby:\n", np.sign(array3))
print("\nOblicza funkcję kroku Heaviside:\n", np.heaviside(array1, array2))
print("\nZwraca koniugat złożony.")
print("Złożony koniugat liczby zespolonej uzyskuje się poprzez zmianę znaku jego części urojonej:\n",
      np.conj(1+2j))
print(np.conjugate(1+2j))
print("\nOblicza wykładnik potęgowy:\n", np.exp(array1))
print("\nPodnosi 2 do podanej potęgi:\n", np.exp2(array1))
print("\nOblicz exp (x) - 1 dla wszystkich elementów w tablicy:\n", np.expm1(array1))

tab1:  [[18  7  5  6 16]]
tab2:  [[14 10  3 16 16]]
tab3:  [2.33, 4.66, -7.5]

Zaokrągla elementy tablicy do najbliższej liczby całkowitej:
 [[18.  7.  5.  6. 16.]]
[ 2.  5. -8.]

Zwraca elementowe oznaczenie znaku liczby:
 [ 1.  1. -1.]

Oblicza funkcję kroku Heaviside:
 [[1. 1. 1. 1. 1.]]

Zwraca koniugat złożony.
Złożony koniugat liczby zespolonej uzyskuje się poprzez zmianę znaku jego części urojonej:
 (1-2j)
(1-2j)

Oblicza wykładnik potęgowy:
 [[6.56599691e+07 1.09663316e+03 1.48413159e+02 4.03428793e+02
  8.88611052e+06]]

Podnosi 2 do podanej potęgi:
 [[2.62144e+05 1.28000e+02 3.20000e+01 6.40000e+01 6.55360e+04]]

Oblicz exp (x) - 1 dla wszystkich elementów w tablicy:
 [[6.56599681e+07 1.09563316e+03 1.47413159e+02 4.02428793e+02
  8.88610952e+06]]


In [19]:
print("tab1: ", array1)
print("tab2: ", array2)

print("\nLogarytm naturalny:\n", np.log(array1))
print("\nLogarytm o podstawie 2:\n", np.log2(array1))
print("\nLogarytm o podstawie dziesiętnej:\n", np.log10(array1))
print("\nZwraca logarytm naturalny jedynki plus tablicę wejściową\n", np.log1p(array1))

print("\nZwraca nieujemny pierwiastek kwadratowy:\n", np.sqrt(array1))
print("\nPodnosi elementy do kwadratu:\n", np.square(array1))
print("\nZwraca pierwiastek sześcienny:\n", np.cbrt(array1))

print("\nZwraca odwrotność argumentu:\n", np.reciprocal([1., 2., 3., 4., 5., 6.]))
print("\nZwraca największy wspólny dzielnik:\n", np.gcd(456646, 8364))
print("\nZwraca najniższą wspólną wielokrotność:\n", np.lcm(456646, 8364))

tab1:  [[18  7  5  6 16]]
tab2:  [[14 10  3 16 16]]

Logarytm naturalny:
 [[2.89037176 1.94591015 1.60943791 1.79175947 2.77258872]]

Logarytm o podstawie 2:
 [[4.169925   2.80735492 2.32192809 2.5849625  4.        ]]

Logarytm o podstawie dziesiętnej:
 [[1.25527251 0.84509804 0.69897    0.77815125 1.20411998]]

Zwraca logarytm naturalny jedynki plus tablicę wejściową
 [[2.94443898 2.07944154 1.79175947 1.94591015 2.83321334]]

Zwraca nieujemny pierwiastek kwadratowy:
 [[4.24264069 2.64575131 2.23606798 2.44948974 4.        ]]

Podnosi elementy do kwadratu:
 [[324  49  25  36 256]]

Zwraca pierwiastek sześcienny:
 [[2.62074139 1.91293118 1.70997595 1.81712059 2.5198421 ]]

Zwraca odwrotność argumentu:
 [1.         0.5        0.33333333 0.25       0.2        0.16666667]

Zwraca największy wspólny dzielnik:
 2

Zwraca najniższą wspólną wielokrotność:
 1909693572
